name: JCMDDelay
version: '${project.version}'
main: jfbdev.jcmddelay.JCMDDelay
api-version: '1.16'
authors: [ jFrostyBoy ]

commands:
  cmddelay:
    description: Отложенное выполнение команды
    usage: /cmddelay <команда> <время>
  jcmddreload:
    description: Перезагрузка плагина
    usage: /jcmddreload

permissions:
  jcmddelay.reload:
    description: Позволяет перезагружать плагин
    default: op